# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['pk'], 'verbose_name': 'юзер', 'verbose_name_plural': 'юзеры'},
        ),
    ]
